- hosts: localhost
  tasks:
    - name: create ec2 instance
      ec2:
        aws_access_key: AKIAIDCGJRSLZI5NZVZA
        aws_secret_key: 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
        key_name: admin
        region: us-east-2
        instance_type: t2.micro
        image: ami-cfdafaaa
        wait: yes
        #group: webserver
        count: 1
        vpc_subnet_id: subnet-4624162f
        assign_public_ip: yes
        group_id: sg-3d49e155
      register: out
      
    - debug:
        msg: "{{out}}"
    
    - add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ out.instances }}"
    
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ out.instances }}"
        
- hosts: launched
  remote_user: ec2-user
  become: yes
  tasks:
    - name: install some packages
      package:
        name: "{{item}}"
        state: installed
      with_items:
        - wget
        - gcc
        - zip 
        - unzip